#!/usr/bin/env python3

"""
Read and process the labels in the sized snapshot output of the `create_iq_snapshot` process  
"""
import argparse
import sys

import pandas as pd
from iqss_gh_reporting import process_labels_util as plu

def main():
    # load argparser
    parser = argparse.ArgumentParser(
    prog='process_labels.py',
    description='Read and process the labels in the sized snapshot output of the `create_iq_snapshot` process',
    epilog='Usage: python process_labels.py --input <infile> --output <ofile> --matrix <matrixfile>')

    parser.add_argument('--input', type=str, help='full path to input file', required=True)
    parser.add_argument('--output', type=str, help='full path to output file', required=True)
    parser.add_argument('--matrix', type=str, help='full path to matrix output file, if desired')
    parser.add_argument('--size_summary', type=str, help='full path to size summary file, if desired')

    args = parser.parse_args()
    # get input file
    infile = args.input
    # get output file
    outfile = args.output
    # get optional matrix file
    matrix = args.matrix
    # get the optional size summary file
    size_summary = args.size_summary

    # read the input file 
    df = plu.read_sized_snapshot(infile)

    # process the labels in the file
    new_df = plu.process_sized_snapshot(df, labels='Labels', key='CardURL')

    # write to matrix file if provided
    if (matrix):
        new_df.to_csv(matrix, sep='\t', index=False)

    # get unique values for column=Column
    values = new_df['Column'].unique()

    # define filter substrings
    substrs = ['This Sprint','In Progress','Ready for Review','In Review']

    # create filter
    filter = plu.create_sprint_filter('Column', values, substrs)

    # summarize a subset of the processed snapshot
    output_df = plu.summarize_processed_sized_snapshot(new_df, filter=filter)

    # write summary to files
    output_df.to_csv(outfile, sep='\t',index=False)

    # create size summary, if requested
    if (size_summary):
        # exclude some fields when modifying values to create the special matrix of sizes
        excluded = ['CardURL','Project','Column','Card',
                    'Type','Number','Labels','Repo','State',
                    'CreatedAt','UpdatedAt','ClosedAt','LinkedPRIssues',
                    'card','Size']
        # create a matrix dataframe using issue size values
        new_matrix_df = plu.create_label_sized_matrix(new_df, size='Size', exclude=excluded)
        # summarize the matrix
        summarized_matrix = plu.summarize_processed_sized_snapshot(new_matrix_df, filter=filter)
        # write summary to file
        summarized_matrix.to_csv(size_summary,sep='\t')

if __name__ == "__main__":
    main()